nombre = input ("Escriba su nombre: ")
print("")
print (f"Hola {nombre} bienvenido al curso de Python de CAE")
print("")
print ("Ahora dime la fecha en que estas viendo este video")
print("")
year = input ("Digita el año: ")
print("")
month = input ("Digita el mes: ")
print("")
day = input ("Digita el dia: ")
print (f"Hoy {day} de {month} del {year} estás viendo este video en Youtube")
print("")
print ("Ahora vamos a sumar dos números")
print ("")
numero1 = int(input("Número 1: "))
print ("")
numero2 = int(input("Número 2: "))
print ("")
print (f"La suma de los dos numeros es ", numero1 + numero2)